//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Core.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [ 订阅通知 ]点位数据更新 的本地化字符串。
        /// </summary>
        public static string @__订阅通知__点位数据更新 {
            get {
                return ResourceManager.GetString("[ 订阅通知 ]点位数据更新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建实例失败，请检查传入的参数 的本地化字符串。
        /// </summary>
        public static string createInstanceErrorTips {
            get {
                return ResourceManager.GetString("createInstanceErrorTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前实例数超过了最大限制（{0}）请检查您的代码是否合理地使用了单例模式 的本地化字符串。
        /// </summary>
        public static string exceedMaxInstanceCountTips {
            get {
                return ResourceManager.GetString("exceedMaxInstanceCountTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检索到 AutoAllocatingTagAttribute 的本地化字符串。
        /// </summary>
        public static string ExistsAutoAllocatingParam_msg1 {
            get {
                return ResourceManager.GetString("ExistsAutoAllocatingParam_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础数据尚未实例化，无法判断是否存在 AutoAllocatingTagAttribute 的本地化字符串。
        /// </summary>
        public static string ExistsAutoAllocatingParam_msg2 {
            get {
                return ResourceManager.GetString("ExistsAutoAllocatingParam_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入 的本地化字符串。
        /// </summary>
        public static string 不支持写入 {
            get {
                return ResourceManager.GetString("不支持写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭失败 的本地化字符串。
        /// </summary>
        public static string 关闭失败 {
            get {
                return ResourceManager.GetString("关闭失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭超时 的本地化字符串。
        /// </summary>
        public static string 关闭超时 {
            get {
                return ResourceManager.GetString("关闭超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入失败 的本地化字符串。
        /// </summary>
        public static string 写入失败 {
            get {
                return ResourceManager.GetString("写入失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入成功 的本地化字符串。
        /// </summary>
        public static string 写入成功 {
            get {
                return ResourceManager.GetString("写入成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据失败 的本地化字符串。
        /// </summary>
        public static string 发送数据失败 {
            get {
                return ResourceManager.GetString("发送数据失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据超时 的本地化字符串。
        /// </summary>
        public static string 发送数据超时 {
            get {
                return ResourceManager.GetString("发送数据超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送等待结果失败 的本地化字符串。
        /// </summary>
        public static string 发送等待结果失败 {
            get {
                return ResourceManager.GetString("发送等待结果失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 的本地化字符串。
        /// </summary>
        public static string 在 {
            get {
                return ResourceManager.GetString("在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string 失败 {
            get {
                return ResourceManager.GetString("失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败信息 的本地化字符串。
        /// </summary>
        public static string 失败信息 {
            get {
                return ResourceManager.GetString("失败信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在 的本地化字符串。
        /// </summary>
        public static string 存在 {
            get {
                return ResourceManager.GetString("存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在数据块发送失败 的本地化字符串。
        /// </summary>
        public static string 存在数据块发送失败 {
            get {
                return ResourceManager.GetString("存在数据块发送失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实例无法创建 的本地化字符串。
        /// </summary>
        public static string 实例无法创建 {
            get {
                return ResourceManager.GetString("实例无法创建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        public static string 客户端 {
            get {
                return ResourceManager.GetString("客户端", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在节点地址 的本地化字符串。
        /// </summary>
        public static string 已存在节点地址 {
            get {
                return ResourceManager.GetString("已存在节点地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已断开连接 的本地化字符串。
        /// </summary>
        public static string 已断开连接 {
            get {
                return ResourceManager.GetString("已断开连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        public static string 已连接 {
            get {
                return ResourceManager.GetString("已连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string 异常 {
            get {
                return ResourceManager.GetString("异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前尚未订阅 的本地化字符串。
        /// </summary>
        public static string 当前尚未订阅 {
            get {
                return ResourceManager.GetString("当前尚未订阅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string 成功 {
            get {
                return ResourceManager.GetString("成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行数据处理异常 的本地化字符串。
        /// </summary>
        public static string 执行数据处理异常 {
            get {
                return ResourceManager.GetString("执行数据处理异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到指定语言 的本地化字符串。
        /// </summary>
        public static string 找不到指定语言 {
            get {
                return ResourceManager.GetString("找不到指定语言", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到资源文件 的本地化字符串。
        /// </summary>
        public static string 找不到资源文件 {
            get {
                return ResourceManager.GetString("找不到资源文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收数据超时 的本地化字符串。
        /// </summary>
        public static string 接收数据超时 {
            get {
                return ResourceManager.GetString("接收数据超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string 文件 {
            get {
                return ResourceManager.GetString("文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取自动分配标识的属性值所对应参数集合 的本地化字符串。
        /// </summary>
        public static string 无法获取自动分配标识的属性值所对应参数集合 {
            get {
                return ResourceManager.GetString("无法获取自动分配标识的属性值所对应参数集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无须指定终端地址 的本地化字符串。
        /// </summary>
        public static string 无须指定终端地址 {
            get {
                return ResourceManager.GetString("无须指定终端地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志参数设置成功 的本地化字符串。
        /// </summary>
        public static string 日志参数设置成功 {
            get {
                return ResourceManager.GetString("日志参数设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无描述 的本地化字符串。
        /// </summary>
        public static string 暂无描述 {
            get {
                return ResourceManager.GetString("暂无描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未接收到数据 的本地化字符串。
        /// </summary>
        public static string 未接收到数据 {
            get {
                return ResourceManager.GetString("未接收到数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未查询到此节点 的本地化字符串。
        /// </summary>
        public static string 未查询到此节点 {
            get {
                return ResourceManager.GetString("未查询到此节点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        public static string 未连接 {
            get {
                return ResourceManager.GetString("未连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询结果为空 的本地化字符串。
        /// </summary>
        public static string 查询结果为空 {
            get {
                return ResourceManager.GetString("查询结果为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败 的本地化字符串。
        /// </summary>
        public static string 添加失败 {
            get {
                return ResourceManager.GetString("添加失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位数据更新异常 的本地化字符串。
        /// </summary>
        public static string 点位数据更新异常 {
            get {
                return ResourceManager.GetString("点位数据更新异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控异常：{0}，断开连接 的本地化字符串。
        /// </summary>
        public static string 监控异常 {
            get {
                return ResourceManager.GetString("监控异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控数据 的本地化字符串。
        /// </summary>
        public static string 监控数据 {
            get {
                return ResourceManager.GetString("监控数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控数据长度错误（小于等于零） 的本地化字符串。
        /// </summary>
        public static string 监控数据错误 {
            get {
                return ResourceManager.GetString("监控数据错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除组失败 的本地化字符串。
        /// </summary>
        public static string 移除组失败 {
            get {
                return ResourceManager.GetString("移除组失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        public static string 第 {
            get {
                return ResourceManager.GetString("第", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string 类型 {
            get {
                return ResourceManager.GetString("类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型错误 的本地化字符串。
        /// </summary>
        public static string 类型错误 {
            get {
                return ResourceManager.GetString("类型错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名不存在 的本地化字符串。
        /// </summary>
        public static string 组名不存在 {
            get {
                return ResourceManager.GetString("组名不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名已存在 的本地化字符串。
        /// </summary>
        public static string 组名已存在 {
            get {
                return ResourceManager.GetString("组名已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        public static string 获取成功 {
            get {
                return ResourceManager.GetString("获取成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string 行 {
            get {
                return ResourceManager.GetString("行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表不存在 的本地化字符串。
        /// </summary>
        public static string 表不存在 {
            get {
                return ResourceManager.GetString("表不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表已经存在 的本地化字符串。
        /// </summary>
        public static string 表已经存在 {
            get {
                return ResourceManager.GetString("表已经存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析异常 的本地化字符串。
        /// </summary>
        public static string 解析异常 {
            get {
                return ResourceManager.GetString("解析异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备不存在 的本地化字符串。
        /// </summary>
        public static string 设备不存在 {
            get {
                return ResourceManager.GetString("设备不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置异常 的本地化字符串。
        /// </summary>
        public static string 语言设置异常 {
            get {
                return ResourceManager.GetString("语言设置异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置成功 的本地化字符串。
        /// </summary>
        public static string 语言设置成功 {
            get {
                return ResourceManager.GetString("语言设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言重复设置 的本地化字符串。
        /// </summary>
        public static string 语言重复设置 {
            get {
                return ResourceManager.GetString("语言重复设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定终端地址 的本地化字符串。
        /// </summary>
        public static string 请指定终端地址 {
            get {
                return ResourceManager.GetString("请指定终端地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求成功 的本地化字符串。
        /// </summary>
        public static string 请求成功 {
            get {
                return ResourceManager.GetString("请求成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败 的本地化字符串。
        /// </summary>
        public static string 读取失败 {
            get {
                return ResourceManager.GetString("读取失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取异常 的本地化字符串。
        /// </summary>
        public static string 读取异常 {
            get {
                return ResourceManager.GetString("读取异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        public static string 连接失败 {
            get {
                return ResourceManager.GetString("连接失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接超时 的本地化字符串。
        /// </summary>
        public static string 连接超时 {
            get {
                return ResourceManager.GetString("连接超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断线重连失败，连接超时，重连{0}次 的本地化字符串。
        /// </summary>
        public static string 重连失败 {
            get {
                return ResourceManager.GetString("重连失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断线重连异常 的本地化字符串。
        /// </summary>
        public static string 重连异常 {
            get {
                return ResourceManager.GetString("重连异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断线重连成功 的本地化字符串。
        /// </summary>
        public static string 重连成功 {
            get {
                return ResourceManager.GetString("重连成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
    }
}
