//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Windows.Controls {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Windows.Controls.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        internal static string 不存在 {
            get {
                return ResourceManager.GetString("不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的图像文件格式 的本地化字符串。
        /// </summary>
        internal static string 不支持的图像文件格式 {
            get {
                return ResourceManager.GetString("不支持的图像文件格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存图片 的本地化字符串。
        /// </summary>
        internal static string 保存图片 {
            get {
                return ResourceManager.GetString("保存图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像保存失败 的本地化字符串。
        /// </summary>
        internal static string 图像保存失败 {
            get {
                return ResourceManager.GetString("图像保存失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础数据 的本地化字符串。
        /// </summary>
        internal static string 基础数据 {
            get {
                return ResourceManager.GetString("基础数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制图片 的本地化字符串。
        /// </summary>
        internal static string 复制图片 {
            get {
                return ResourceManager.GetString("复制图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string 导入 {
            get {
                return ResourceManager.GetString("导入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string 导出 {
            get {
                return ResourceManager.GetString("导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在 的本地化字符串。
        /// </summary>
        internal static string 已存在 {
            get {
                return ResourceManager.GetString("已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string 异常 {
            get {
                return ResourceManager.GetString("异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮肤设置成功 的本地化字符串。
        /// </summary>
        internal static string 皮肤设置成功 {
            get {
                return ResourceManager.GetString("皮肤设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string 确认 {
            get {
                return ResourceManager.GetString("确认", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除线条 的本地化字符串。
        /// </summary>
        internal static string 移除线条 {
            get {
                return ResourceManager.GetString("移除线条", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除线条值 的本地化字符串。
        /// </summary>
        internal static string 移除线条值 {
            get {
                return ResourceManager.GetString("移除线条值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线条操作 的本地化字符串。
        /// </summary>
        internal static string 线条操作 {
            get {
                return ResourceManager.GetString("线条操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整 的本地化字符串。
        /// </summary>
        internal static string 调整 {
            get {
                return ResourceManager.GetString("调整", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string 重置 {
            get {
                return ResourceManager.GetString("重置", resourceCulture);
            }
        }
    }
}
