using System.Windows.Markup;
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.button")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.textbox")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.combobox")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.property")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.property.wpf")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.converter")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.ledgauge")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.pagebar")]
[assembly: XmlnsDefinition("https://snet.cn", "Snet.Windows.Controls.tray.Controls")]
